const listaPalabras = [
  'zero','0 IN ENGLISH',
  'one', '1 IN ENGLISH',
  'two', '2 IN ENGLISH',
  'tree', '3 IN ENGLISH',
  'for', '4 IN ENGLISH',
  'five', '5 IN ENGLISH',
  'six','6 IN ENGLISH',
  'seven','7 IN ENGLISH',
  'eight','8 IN ENGLISH',
  'nine','9 IN ENGLISH',
  'ten','10 IN ENGLISH',
  'fifteen','15 IN ENGLISH',
  'twenty','20 IN ENGLISH',
  'twenty-one','21 IN ENGLISH',
  'thirty','30 IN ENGLISH',
  'thirty-two','32 IN ENGLISH',
  'forty','40 IN ENGLISH',
  'forty-three','43 IN ENGLISH',
  'fifty','50 IN ENGLISH',
  'fifty-four','54 IN ENGLISH',
  'sixty','60 IN ENGLISH',
  'sixty-five','65 IN ENGLISH',
  'seventy','70 IN ENGLISH',
  'seventy-six','76 IN ENGLISH',
  'eighty','80 IN ENGLISH',
  'eighty-seven','87 IN ENGLISH',
  'ninety','90 IN ENGLISH',
  'ninety-eight','98 IN ENGLISH',
  'one hundred','100 IN ENGLISH',
];
